spring:
  datasource:
    url: jdbc:mariadb://parkjaemin.czqpiiaxuzcd.ap-northeast-2.rds.amazonaws.com:3306/ParkJaemin
    driver-class-name: org.mariadb.jdbc.Driver
    username: ParkJaemin
    password: woals1212!
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update